name: run
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run]
    workflow_dispatch:
jobs:
    run1:
      runs-on: ubuntu-20.04
      timeout-minutes: 60
      steps:
      - uses: actions/checkout@v3
      - name: prepairing and run
        run: bash start.sh
      env:
        NAME: ${{secrets.NAME}}
        DOWNLOADS: ${{secrets.DOWNLOADS}}
        CLI: ${{secrets.CLI}}
        DIS: ${{secrets.DIS}}
        EXTRACT1: ${{secrets.EXTRACT1}}
        EXTRACT2: ${{secrets.EXTRACT2}}
        MISCDOWNLOADS: ${{secrets.MISCDOWNLOADS}}
        REQUIREMENTS: ${{secrets.REQUIREMENTS}}
        
