name: run
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run]
    workflow_dispatch:
jobs:
    run1:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
      - uses: actions/checkout@v3
      - name: prepairing and run
        run: bash start.sh
      env:
        NAME: ${{secrets.NAME}}
        DOWNLOADS: ${{secrets.DOWNLOADS}}
